### ISSUE TITLE
Owncast Directory content

### ISSUE THREAD

**Issue by gabek** [bitsbb01/IPTV-M3US#5]
Feel free to add the IPTV feed for the Owncast directory:

https://directory.owncast.online/api/iptv

It updates as people go on and offline, so you should refresh it often in your application.

**Comment by bitsbb01** [comment]
thanks, i'll add it to https://github.com/bitsbb01/m3u8_creator so it auto updates every 3hrs automaticly...

**Comment by bitsbb01** [comment]
closing.
